# Generated by Django 5.1.7 on 2025-03-18 16:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('d_title', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z]{2,24}$', 'Title faqat harflardan iborat bo‘lishi va bosh harfi katta bo‘lishi kerak!')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z]{2,24}$', 'Title faqat harflardan iborat bo‘lishi va bosh harfi katta bo‘lishi kerak!')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Employes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z]{2,24}$', 'Familya faqat harflardan iborat bo‘lishi va bosh harfi katta bo‘lishi kerak!')])),
                ('first_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z]{2,24}$', 'Ism faqat harflardan iborat bo‘lishi va bosh harfi katta bo‘lishi kerak!')])),
                ('midle_name', models.CharField(max_length=40, validators=[django.core.validators.RegexValidator('^[A-Z][a-zA-Z]{2,24}$', 'Ism faqat harflardan iborat bo‘lishi va bosh harfi katta bo‘lishi kerak!')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqami +998 bilan boshlanib, jami 13 ta belgidan iborat bo‘lishi kerak!', regex='^\\+998\\d{9}$')])),
                ('data_fild', models.FileField(upload_to='uplods/', validators=[django.core.validators.RegexValidator(message='Telefon raqami +998 bilan boshlanib, jami 13 ta belgidan iborat bo‘lishi kerak!', regex='\\(pff|docx?)$')])),
                ('fk_departamen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.departament')),
                ('fk_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.region')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
